In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px

In [2]:
# read and understand columns
i = 2015

while i != 2018:

    globals()[f'df{i}'] = pd.read_csv(f'{i}.csv')
    i += 1

while i != 2024:

    globals()[f'df{i}'] = pd.read_excel(f'{i}.xls')
    i+=1

FileNotFoundError: [Errno 2] No such file or directory: '2015.csv'

In [ ]:
df2015

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [ ]:
df2016

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,Southern Asia,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,Sub-Saharan Africa,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,Middle East and Northern Africa,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,Sub-Saharan Africa,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [ ]:
df2017

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [ ]:
df2018

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Finland,7.6321,7.694913,7.569287,2.595186,1.305095,1.592134,0.874454,0.680633,0.191638,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,country
1,Norway,7.5937,7.657077,7.530323,2.383242,1.455627,1.582340,0.860763,0.686420,0.285636,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland
2,Denmark,7.5553,7.623292,7.487309,2.370179,1.351153,1.590453,0.867933,0.683251,0.284392,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Iceland,7.4952,7.592534,7.397867,2.425990,1.343301,1.644378,0.913802,0.676502,0.353233,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Denmark
4,Switzerland,7.4873,7.569994,7.404606,2.319529,1.419727,1.548998,0.927076,0.659779,0.255525,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Iceland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Tanzania,3.3035,3.413903,3.193097,0.628085,0.454864,0.991134,0.381297,0.480925,0.270037,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yemen
153,South Sudan,3.2542,3.385097,3.123303,1.690625,0.337370,0.607502,0.177460,0.111604,0.223926,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tanzania
154,Central African Republic,3.0830,3.226582,2.939418,2.487011,0.023905,0.000000,0.010100,0.305280,0.218356,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Sudan
155,Burundi,2.9045,3.074190,2.734810,1.751794,0.090806,0.626902,0.145325,0.064850,0.148904,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Central African Republic
156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Burundi

In [ ]:
df2019

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.88) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.7689,7.829888,7.707912,2.713678,1.340243,1.587276,0.986145,0.595895,0.152708,0.392913
1,Denmark,7.6001,7.666658,7.533542,2.392891,1.383439,1.572595,0.996019,0.592356,0.252320,0.410473
2,Norway,7.5539,7.615639,7.492160,2.240764,1.487767,1.581548,1.028123,0.603500,0.271304,0.340884
3,Iceland,7.4936,7.613283,7.373917,2.400876,1.380163,1.623651,1.025653,0.590905,0.354356,0.117980
4,Netherlands,7.4876,7.542098,7.433102,2.392895,1.396020,1.521903,0.999314,0.557075,0.322440,0.297978
...,...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,3.3338,3.425188,3.242412,0.467255,0.359488,0.711048,0.613996,0.554570,0.216655,0.410826
152,Tanzania,3.2307,3.347133,3.114267,0.530644,0.475854,0.884855,0.498773,0.417151,0.276294,0.147167
153,Afghanistan,3.2033,3.277512,3.129088,1.793060,0.349631,0.517003,0.360616,0.000000,0.158151,0.024875
154,Central African Republic,3.0830,3.226582,2.939418,2.455649,0.026408,0.000000,0.105346,0.225277,0.235050,0.035268
155,South Sudan,2.8526,3.004615,2.700585,1.374341,0.305843,0.574936,0.294648,0.010214,0.202084,0.090529

In [ ]:
df2020

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900826,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,0.115183,3.701658,3.250141,6.625160,0.319460,45.200001,0.640881,0.082410,0.891807,1.972317,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,Rwanda,Sub-Saharan Africa,3.3123,0.052425,3.415053,3.209547,7.600104,0.540835,61.098846,0.900589,0.055484,0.183541,1.972317,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.058674,3.414202,3.184198,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237,1.972317,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,South Sudan,Sub-Saharan Africa,2.8166,0.107610,3.027516,2.605684,7.425360,0.553707,51.000000,0.451314,0.016519,0.763417,1.972317,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,Afghanistan,South Asia,2.5669,0.031311,2.628270,2.505530,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687,1.972317,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [ ]:
df2021

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8421,0.031646,7.904126,7.780075,10.775202,0.953603,72.000000,0.949268,-0.097760,0.185846,2.430343,1.446356,1.106192,0.740824,0.690577,0.124200,0.480524,3.253415
1,Denmark,Western Europe,7.6195,0.034657,7.687428,7.551572,10.933176,0.954410,72.699753,0.945639,0.030109,0.178838,2.430343,1.501548,1.108008,0.762862,0.686160,0.207615,0.484993,2.868296
2,Switzerland,Western Europe,7.5715,0.036243,7.642536,7.500463,11.117368,0.941742,74.400101,0.918788,0.024629,0.291698,2.430343,1.565899,1.079469,0.816415,0.653488,0.204040,0.413019,2.839148
3,Iceland,Western Europe,7.5539,0.059373,7.670271,7.437528,10.877768,0.982938,73.000000,0.955123,0.160274,0.672865,2.430343,1.482190,1.172279,0.772319,0.697701,0.292526,0.169940,2.966945
4,Netherlands,Western Europe,7.4640,0.027326,7.517559,7.410441,10.931812,0.941601,72.400116,0.913116,0.175404,0.337938,2.430343,1.501072,1.079151,0.753425,0.646585,0.302397,0.383531,2.797818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.5118,0.120454,3.747890,3.275710,7.925777,0.786871,48.700001,0.714954,-0.130536,0.915377,2.430343,0.450848,0.730561,0.006992,0.405455,0.102819,0.015284,1.799821
145,Botswana,Sub-Saharan Africa,3.4665,0.073872,3.611289,3.321711,9.781536,0.784171,59.269188,0.824394,-0.246159,0.800619,2.430343,1.099198,0.724478,0.339868,0.538626,0.027394,0.088468,0.648460
146,Rwanda,Sub-Saharan Africa,3.4147,0.067830,3.547647,3.281753,7.676118,0.552339,61.399727,0.896758,0.060526,0.166801,2.430343,0.363624,0.202183,0.406969,0.626681,0.227457,0.492669,1.095149
147,Zimbabwe,Sub-Saharan Africa,3.1448,0.058443,3.259349,3.030251,7.942595,0.750470,56.200840,0.676700,-0.047346,0.820999,2.430343,0.456724,0.648552,0.243230,0.358907,0.157088,0.075471,1.204845
148,Afghanistan,South Asia,2.5229,0.037535,2.596468,2.449332,7.694710,0.462596,52.492615,0.381749,-0.101684,0.924338,2.430343,0.370120,0.000000,0.126440,0.000000,0.121641,0.009569,1.895141

In [ ]:
df2022

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,7.8210,7.886425,7.755575,2.518052,1.891628,1.258108,0.775206,0.735590,0.108733,0.533658
1,2,Denmark,7.6362,7.709897,7.562503,2.225632,1.952595,1.242681,0.776644,0.718918,0.187626,0.532079
2,3,Iceland,7.5575,7.651076,7.463924,2.320185,1.935726,1.319914,0.802622,0.718194,0.269616,0.191204
3,4,Switzerland,7.5116,7.586394,7.436806,2.152746,2.025970,1.226074,0.822048,0.676947,0.146822,0.461004
4,5,Netherlands,7.4149,7.471265,7.358534,2.136937,1.944578,1.205848,0.786738,0.650682,0.271076,0.419083
...,...,...,...,...,...,...,...,...,...,...,...,...
142,143,Rwanda*,3.2682,3.462218,3.074182,0.536299,0.785252,0.132698,0.461527,0.621479,0.186662,0.544236
143,144,Zimbabwe,2.9951,3.109822,2.880378,0.547529,0.946604,0.690460,0.270086,0.329203,0.106265,0.104943
144,145,Lebanon,2.9553,3.048951,2.861649,0.215537,1.392068,0.497999,0.630964,0.102799,0.082191,0.033761
145,146,Afghanistan,2.4038,2.468731,2.338869,1.263403,0.757994,0.000000,0.288626,0.000000,0.088873,0.004882
146,147,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2023

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.8042,0.036162,7.875078,7.733322,10.792010,0.968770,71.149994,0.961408,-0.018824,0.181745,1.777825,1.888380,1.584900,0.534574,0.771510,0.126331,0.535299,2.363241
1,Denmark,7.5864,0.041028,7.666815,7.505985,10.962164,0.954112,71.250145,0.933533,0.134242,0.195814,1.777825,1.949406,1.547875,0.537302,0.734416,0.208459,0.525221,2.083766
2,Iceland,7.5296,0.048612,7.624879,7.434321,10.895531,0.982533,72.050018,0.936349,0.210987,0.667848,1.777825,1.925508,1.619666,0.559096,0.738164,0.249635,0.187119,2.250382
3,Israel,7.4729,0.031609,7.534853,7.410946,10.638705,0.943344,72.697205,0.808866,-0.023080,0.708094,1.777825,1.833398,1.520674,0.576730,0.568518,0.124048,0.158292,2.691290
4,Netherlands,7.4030,0.029294,7.460416,7.345583,10.942279,0.930499,71.550018,0.886875,0.212686,0.378929,1.777825,1.942274,1.488228,0.545473,0.672327,0.250547,0.394062,2.110044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),3.2072,0.095369,3.394124,3.020277,7.006671,0.651610,55.375000,0.663798,0.085998,0.833752,1.777825,0.530779,0.783747,0.104758,0.375472,0.182573,0.068287,1.161580
133,Zimbabwe,3.2035,0.060865,3.322795,3.084205,7.640998,0.689918,54.049889,0.654055,-0.046230,0.765582,1.777825,0.758279,0.880513,0.068653,0.362508,0.111627,0.117115,0.904856
134,Sierra Leone,3.1376,0.082441,3.299184,2.976016,7.394014,0.555251,54.899853,0.660367,0.104929,0.857780,1.777825,0.669699,0.540343,0.091811,0.370907,0.192731,0.051077,1.221006
135,Lebanon,2.3922,0.044495,2.479410,2.304990,9.477677,0.529754,66.148819,0.473900,-0.140915,0.891104,1.777825,1.416999,0.475936,0.398308,0.122771,0.060824,0.027208,-0.109798
136,Afghanistan,1.8590,0.032506,1.922712,1.795288,7.324032,0.341341,54.712410,0.381642,-0.081011,0.847215,1.777825,0.644600,0.000000,0.086704,0.000000,0.092965,0.058644,0.976065

In [ ]:
# data cleanning

df2015 = df2015.drop('Standard Error', axis=1)

In [ ]:
df2016 = df2016.drop(['Lower Confidence Interval', 'Upper Confidence Interval'], axis=1)
df2016

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,Southern Asia,154,3.360,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,Sub-Saharan Africa,155,3.303,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,Middle East and Northern Africa,156,3.069,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,Sub-Saharan Africa,157,2.905,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [ ]:
columns = ['Country', 'Region', 'Happiness Rank', 'Happiness Score',	'Economy (GDP per Capita)',	'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']

df2017 = df2017.drop(['Whisker.high','Whisker.low'],axis=1)

columns_mapping = {
    'Happiness.Rank' : 'Happiness Rank',
    'Happiness.Score' :'Happiness Score',
    'Economy..GDP.per.Capita.' : 'Economy (GDP per Capita)',
    'Family' : 'Family',
    'Health..Life.Expectancy.' : 'Health (Life Expectancy)',
    'Freedom' : "Freedom",
    'Generosity': 'Generosity',
    'Trust..Government.Corruption.' : 'Trust (Government Corruption)',
    'Dystopia.Residual' : 'Dystopia Residual'
    
}

df2017.rename(columns=columns_mapping, inplace=True)

merged_df = pd.merge(df2017, df2016[['Country', 'Region']], on='Country', how='left')

merged_df = merged_df[columns]

df2017 = merged_df

df2017

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Norway,Western Europe,1,7.537,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027
1,Denmark,Western Europe,2,7.522,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707
2,Iceland,Western Europe,3,7.504,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715
3,Switzerland,Western Europe,4,7.494,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716
4,Finland,Western Europe,5,7.469,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483,2.430182
...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,Sub-Saharan Africa,151,3.471,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756,0.540061
151,Syria,Middle East and Northern Africa,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1.061574
152,Tanzania,Sub-Saharan Africa,153,3.349,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256,0.621130
153,Burundi,Sub-Saharan Africa,154,2.905,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435,1.683024
154,Central African Republic,NaN,155,2.693,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005

In [ ]:
df2018_copy  = df2018

In [ ]:
df2018_copy =df2018_copy.dropna(axis=1, how='all')
df2018_copy.dropna(axis=0, thresh=4, inplace=True)
df2018_copy
df2018_copy.drop(['Whisker-high', 'Whisker-low', 'Unnamed: 23'], axis=1, inplace=True)
df2018_copy

<ipython-input-154-4ab2d52c86b0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2018_copy.dropna(axis=0, thresh=4, inplace=True)
<ipython-input-154-4ab2d52c86b0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2018_copy.drop(['Whisker-high', 'Whisker-low', 'Unnamed: 23'], axis=1, inplace=True)

,Country,Happiness score,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.6321,2.595186,1.305095,1.592134,0.874454,0.680633,0.191638,0.392961
1,Norway,7.5937,2.383242,1.455627,1.582340,0.860763,0.686420,0.285636,0.339687
2,Denmark,7.5553,2.370179,1.351153,1.590453,0.867933,0.683251,0.284392,0.407917
3,Iceland,7.4952,2.425990,1.343301,1.644378,0.913802,0.676502,0.353233,0.138019
4,Switzerland,7.4873,2.319529,1.419727,1.548998,0.927076,0.659779,0.255525,0.356677
...,...,...,...,...,...,...,...,...,...
151,Yemen,3.3549,1.106474,0.441527,1.072613,0.343216,0.243870,0.083092,0.064146
152,Tanzania,3.3035,0.628085,0.454864,0.991134,0.381297,0.480925,0.270037,0.097195
153,South Sudan,3.2542,1.690625,0.337370,0.607502,0.177460,0.111604,0.223926,0.105675
154,Central African Republic,3.0830,2.487011,0.023905,0.000000,0.010100,0.305280,0.218356,0.038344
155,Burundi,2.9045,1.751794,0.090806,0.626902,0.145325,0.064850,0.148904,0.075953

In [ ]:
columns_mapping = {
    'Happiness score' : 'Happiness Score',
    'Dystopia (1.92) + residual': 'Dystopia Residual',
    'Explained by: GDP per capita': 'Economy (GDP per Capita)',
    'Explained by: Social support': 'Family',
    'Explained by: Healthy life expectancy': 'Health (Life Expectancy)',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Generosity': 'Generosity',
    'Explained by: Perceptions of corruption' : 'Trust (Government Corruption)'
}
df2018_copy.rename(columns=columns_mapping, inplace=True)
df2018_copy.insert(2, 'Happiness Rank', [None] * len(df2018_copy))
columns = ['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)',	'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']

merged_df = pd.merge(df2018_copy, df2016[['Country', 'Region']], on='Country', how='left')

merged_df = merged_df[columns]


merged_df['Happiness Rank'] = range(1,157)


df2018 = merged_df
df2018

<ipython-input-155-092bd1e04676>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2018_copy.rename(columns=columns_mapping, inplace=True)

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Finland,Western Europe,1,7.6321,1.305095,1.592134,0.874454,0.680633,0.392961,0.191638,2.595186
1,Norway,Western Europe,2,7.5937,1.455627,1.582340,0.860763,0.686420,0.339687,0.285636,2.383242
2,Denmark,Western Europe,3,7.5553,1.351153,1.590453,0.867933,0.683251,0.407917,0.284392,2.370179
3,Iceland,Western Europe,4,7.4952,1.343301,1.644378,0.913802,0.676502,0.138019,0.353233,2.425990
4,Switzerland,Western Europe,5,7.4873,1.419727,1.548998,0.927076,0.659779,0.356677,0.255525,2.319529
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,Middle East and Northern Africa,152,3.3549,0.441527,1.072613,0.343216,0.243870,0.064146,0.083092,1.106474
152,Tanzania,Sub-Saharan Africa,153,3.3035,0.454864,0.991134,0.381297,0.480925,0.097195,0.270037,0.628085
153,South Sudan,Sub-Saharan Africa,154,3.2542,0.337370,0.607502,0.177460,0.111604,0.105675,0.223926,1.690625
154,Central African Republic,NaN,155,3.0830,0.023905,0.000000,0.010100,0.305280,0.038344,0.218356,2.487011
155,Burundi,Sub-Saharan Africa,156,2.9045,0.090806,0.626902,0.145325,0.064850,0.075953,0.148904,1.751794

In [ ]:
df2019

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.88) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.7689,7.829888,7.707912,2.713678,1.340243,1.587276,0.986145,0.595895,0.152708,0.392913
1,Denmark,7.6001,7.666658,7.533542,2.392891,1.383439,1.572595,0.996019,0.592356,0.252320,0.410473
2,Norway,7.5539,7.615639,7.492160,2.240764,1.487767,1.581548,1.028123,0.603500,0.271304,0.340884
3,Iceland,7.4936,7.613283,7.373917,2.400876,1.380163,1.623651,1.025653,0.590905,0.354356,0.117980
4,Netherlands,7.4876,7.542098,7.433102,2.392895,1.396020,1.521903,0.999314,0.557075,0.322440,0.297978
...,...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,3.3338,3.425188,3.242412,0.467255,0.359488,0.711048,0.613996,0.554570,0.216655,0.410826
152,Tanzania,3.2307,3.347133,3.114267,0.530644,0.475854,0.884855,0.498773,0.417151,0.276294,0.147167
153,Afghanistan,3.2033,3.277512,3.129088,1.793060,0.349631,0.517003,0.360616,0.000000,0.158151,0.024875
154,Central African Republic,3.0830,3.226582,2.939418,2.455649,0.026408,0.000000,0.105346,0.225277,0.235050,0.035268
155,South Sudan,2.8526,3.004615,2.700585,1.374341,0.305843,0.574936,0.294648,0.010214,0.202084,0.090529

In [ ]:
def clean(df):
    copy = df
    copy.drop(['Whisker-high', 'Whisker-low'], axis=1, inplace=True)
    columns_mapping = {
    'Happiness score' : 'Happiness Score',
    'Dystopia (1.88) + residual': 'Dystopia Residual',
    'Explained by: GDP per capita': 'Economy (GDP per Capita)',
    'Explained by: Social support': 'Family',
    'Explained by: Healthy life expectancy': 'Health (Life Expectancy)',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Generosity': 'Generosity',
    'Explained by: Perceptions of corruption' : 'Trust (Government Corruption)'
}
    copy.rename(columns=columns_mapping, inplace=True)
    copy.insert(2, 'Happiness Rank', [None] * len(df2018_copy))
    columns = ['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)',	'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']

    merged_df = pd.merge(copy, df2016[['Country', 'Region']], on='Country', how='left')

    merged_df = merged_df[columns]


    merged_df['Happiness Rank'] = range(1,157)


    df = merged_df

    return df

In [ ]:
df2019 = clean(df2019)
df2019

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Finland,Western Europe,1,7.7689,1.340243,1.587276,0.986145,0.595895,0.392913,0.152708,2.713678
1,Denmark,Western Europe,2,7.6001,1.383439,1.572595,0.996019,0.592356,0.410473,0.252320,2.392891
2,Norway,Western Europe,3,7.5539,1.487767,1.581548,1.028123,0.603500,0.340884,0.271304,2.240764
3,Iceland,Western Europe,4,7.4936,1.380163,1.623651,1.025653,0.590905,0.117980,0.354356,2.400876
4,Netherlands,Western Europe,5,7.4876,1.396020,1.521903,0.999314,0.557075,0.297978,0.322440,2.392895
...,...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,Sub-Saharan Africa,152,3.3338,0.359488,0.711048,0.613996,0.554570,0.410826,0.216655,0.467255
152,Tanzania,Sub-Saharan Africa,153,3.2307,0.475854,0.884855,0.498773,0.417151,0.147167,0.276294,0.530644
153,Afghanistan,Southern Asia,154,3.2033,0.349631,0.517003,0.360616,0.000000,0.024875,0.158151,1.793060
154,Central African Republic,NaN,155,3.0830,0.026408,0.000000,0.105346,0.225277,0.035268,0.235050,2.455649
155,South Sudan,Sub-Saharan Africa,156,2.8526,0.305843,0.574936,0.294648,0.010214,0.090529,0.202084,1.374341

In [ ]:
df2020

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900826,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,0.115183,3.701658,3.250141,6.625160,0.319460,45.200001,0.640881,0.082410,0.891807,1.972317,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,Rwanda,Sub-Saharan Africa,3.3123,0.052425,3.415053,3.209547,7.600104,0.540835,61.098846,0.900589,0.055484,0.183541,1.972317,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.058674,3.414202,3.184198,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237,1.972317,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,South Sudan,Sub-Saharan Africa,2.8166,0.107610,3.027516,2.605684,7.425360,0.553707,51.000000,0.451314,0.016519,0.763417,1.972317,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,Afghanistan,South Asia,2.5669,0.031311,2.628270,2.505530,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687,1.972317,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [ ]:
df2020_copy = df2020

df2020_copy.drop(['Standard error of ladder score',	'upperwhisker',	'lowerwhisker',	'Logged GDP per capita', 'Social support',	'Healthy life expectancy',	'Freedom to make life choices',	'Generosity',	'Perceptions of corruption',	'Ladder score in Dystopia'], axis=1, inplace=True)

columns_mapping= { 
    'Country name': 'Country',
    'Regional indicator' : 'Region',
    'Ladder score': 'Happiness Score',
    'Explained by: Log GDP per capita': 'Economy (GDP per Capita)',
    'Explained by: Social support': 'Family',
    'Explained by: Healthy life expectancy': 'Health (Life Expectancy)',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Generosity': 'Generosity',
    'Explained by: Perceptions of corruption' : 'Trust (Government Corruption)'
    
}

df2020_copy.rename(columns=columns_mapping, inplace=True)
df2020_copy.insert(2, 'Happiness Rank', [None] * len(df2020_copy))
df2020_copy['Happiness Rank'] = range(1, len(df2020_copy)+1)
df2020 = df2020_copy

In [ ]:
df2021_copy = df2021

df2021_copy.drop(['Standard error of ladder score',	'upperwhisker',	'lowerwhisker',	'Logged GDP per capita', 'Social support',	'Healthy life expectancy',	'Freedom to make life choices',	'Generosity',	'Perceptions of corruption',	'Ladder score in Dystopia'], axis=1, inplace=True)
columns_mapping= { 
    'Country name': 'Country',
    'Regional indicator' : 'Region',
    'Ladder score': 'Happiness Score',
    'Explained by: Log GDP per capita': 'Economy (GDP per Capita)',
    'Explained by: Social support': 'Family',
    'Explained by: Healthy life expectancy': 'Health (Life Expectancy)',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Generosity': 'Generosity',
    'Explained by: Perceptions of corruption' : 'Trust (Government Corruption)'
}
df2021_copy.rename(columns=columns_mapping, inplace=True)
df2021_copy.insert(2, 'Happiness Rank', [None] * len(df2021_copy))
df2021_copy['Happiness Rank'] = range(1, len(df2021_copy)+1)
df2021 = df2021_copy
df2021

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia + residual
0,Finland,Western Europe,1,7.8421,1.446356,1.106192,0.740824,0.690577,0.124200,0.480524,3.253415
1,Denmark,Western Europe,2,7.6195,1.501548,1.108008,0.762862,0.686160,0.207615,0.484993,2.868296
2,Switzerland,Western Europe,3,7.5715,1.565899,1.079469,0.816415,0.653488,0.204040,0.413019,2.839148
3,Iceland,Western Europe,4,7.5539,1.482190,1.172279,0.772319,0.697701,0.292526,0.169940,2.966945
4,Netherlands,Western Europe,5,7.4640,1.501072,1.079151,0.753425,0.646585,0.302397,0.383531,2.797818
...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,145,3.5118,0.450848,0.730561,0.006992,0.405455,0.102819,0.015284,1.799821
145,Botswana,Sub-Saharan Africa,146,3.4665,1.099198,0.724478,0.339868,0.538626,0.027394,0.088468,0.648460
146,Rwanda,Sub-Saharan Africa,147,3.4147,0.363624,0.202183,0.406969,0.626681,0.227457,0.492669,1.095149
147,Zimbabwe,Sub-Saharan Africa,148,3.1448,0.456724,0.648552,0.243230,0.358907,0.157088,0.075471,1.204845
148,Afghanistan,South Asia,149,2.5229,0.370120,0.000000,0.126440,0.000000,0.121641,0.009569,1.895141

In [ ]:
df2022

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,7.8210,7.886425,7.755575,2.518052,1.891628,1.258108,0.775206,0.735590,0.108733,0.533658
1,2,Denmark,7.6362,7.709897,7.562503,2.225632,1.952595,1.242681,0.776644,0.718918,0.187626,0.532079
2,3,Iceland,7.5575,7.651076,7.463924,2.320185,1.935726,1.319914,0.802622,0.718194,0.269616,0.191204
3,4,Switzerland,7.5116,7.586394,7.436806,2.152746,2.025970,1.226074,0.822048,0.676947,0.146822,0.461004
4,5,Netherlands,7.4149,7.471265,7.358534,2.136937,1.944578,1.205848,0.786738,0.650682,0.271076,0.419083
...,...,...,...,...,...,...,...,...,...,...,...,...
142,143,Rwanda*,3.2682,3.462218,3.074182,0.536299,0.785252,0.132698,0.461527,0.621479,0.186662,0.544236
143,144,Zimbabwe,2.9951,3.109822,2.880378,0.547529,0.946604,0.690460,0.270086,0.329203,0.106265,0.104943
144,145,Lebanon,2.9553,3.048951,2.861649,0.215537,1.392068,0.497999,0.630964,0.102799,0.082191,0.033761
145,146,Afghanistan,2.4038,2.468731,2.338869,1.263403,0.757994,0.000000,0.288626,0.000000,0.088873,0.004882
146,147,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2022_copy = df2022

df2022_copy.drop(['Whisker-high', 'Whisker-low'], axis=1, inplace = True)
columns_mapping= {
    'RANK' : 'Happiness Rank',
    'Happiness score' : 'Happiness Score',
    'Dystopia (1.83) + residual': 'Dystopia Residual',
    'Explained by: GDP per capita': 'Economy (GDP per Capita)',
    'Explained by: Social support': 'Family',
    'Explained by: Healthy life expectancy': 'Health (Life Expectancy)',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Generosity': 'Generosity',
    'Explained by: Perceptions of corruption' : 'Trust (Government Corruption)'
}


columns = ['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)',	'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']

df2022_copy.rename(columns=columns_mapping, inplace=True)

merged_df = pd.merge(df2022_copy, df2016[['Country', 'Region']], on='Country', how='left')

merged_df = merged_df[columns]
df2022_copy = merged_df[columns]
df2022_copy.drop(df2022_copy.index[-1], inplace=True)
df2022_copy
df2022 = df2022_copy

In [ ]:
df2023

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.8042,0.036162,7.875078,7.733322,10.792010,0.968770,71.149994,0.961408,-0.018824,0.181745,1.777825,1.888380,1.584900,0.534574,0.771510,0.126331,0.535299,2.363241
1,Denmark,7.5864,0.041028,7.666815,7.505985,10.962164,0.954112,71.250145,0.933533,0.134242,0.195814,1.777825,1.949406,1.547875,0.537302,0.734416,0.208459,0.525221,2.083766
2,Iceland,7.5296,0.048612,7.624879,7.434321,10.895531,0.982533,72.050018,0.936349,0.210987,0.667848,1.777825,1.925508,1.619666,0.559096,0.738164,0.249635,0.187119,2.250382
3,Israel,7.4729,0.031609,7.534853,7.410946,10.638705,0.943344,72.697205,0.808866,-0.023080,0.708094,1.777825,1.833398,1.520674,0.576730,0.568518,0.124048,0.158292,2.691290
4,Netherlands,7.4030,0.029294,7.460416,7.345583,10.942279,0.930499,71.550018,0.886875,0.212686,0.378929,1.777825,1.942274,1.488228,0.545473,0.672327,0.250547,0.394062,2.110044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),3.2072,0.095369,3.394124,3.020277,7.006671,0.651610,55.375000,0.663798,0.085998,0.833752,1.777825,0.530779,0.783747,0.104758,0.375472,0.182573,0.068287,1.161580
133,Zimbabwe,3.2035,0.060865,3.322795,3.084205,7.640998,0.689918,54.049889,0.654055,-0.046230,0.765582,1.777825,0.758279,0.880513,0.068653,0.362508,0.111627,0.117115,0.904856
134,Sierra Leone,3.1376,0.082441,3.299184,2.976016,7.394014,0.555251,54.899853,0.660367,0.104929,0.857780,1.777825,0.669699,0.540343,0.091811,0.370907,0.192731,0.051077,1.221006
135,Lebanon,2.3922,0.044495,2.479410,2.304990,9.477677,0.529754,66.148819,0.473900,-0.140915,0.891104,1.777825,1.416999,0.475936,0.398308,0.122771,0.060824,0.027208,-0.109798
136,Afghanistan,1.8590,0.032506,1.922712,1.795288,7.324032,0.341341,54.712410,0.381642,-0.081011,0.847215,1.777825,0.644600,0.000000,0.086704,0.000000,0.092965,0.058644,0.976065

In [ ]:
df2023_copy = df2023

df2023_copy.drop(['Standard error of ladder score',	'upperwhisker',	'lowerwhisker',	'Logged GDP per capita', 'Social support',	'Healthy life expectancy',	'Freedom to make life choices',	'Generosity',	'Perceptions of corruption',	'Ladder score in Dystopia'], axis=1, inplace = True)
columns_mapping= { 
    'Country name': 'Country',
    'Regional indicator' : 'Region',
    'Ladder score': 'Happiness Score',
    'Explained by: Log GDP per capita': 'Economy (GDP per Capita)',
    'Explained by: Social support': 'Family',
    'Explained by: Healthy life expectancy': 'Health (Life Expectancy)',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Generosity': 'Generosity',
    'Explained by: Perceptions of corruption' : 'Trust (Government Corruption)',
    'Dystopia + residual' : 'Dystopia Residual'
}
df2023_copy.rename(columns=columns_mapping, inplace=True)
df2023_copy.insert(2, 'Happiness Rank', [None] * len(df2023_copy))
df2023_copy['Happiness Rank'] = range(1, len(df2023_copy)+1)
merged_df = pd.merge(df2023_copy, df2016[['Country', 'Region']], on='Country', how='left')
columns = ['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)',	'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']
merged_df = merged_df[columns]

df2023 = merged_df
df2023

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Finland,Western Europe,1,7.8042,1.888380,1.584900,0.534574,0.771510,0.535299,0.126331,2.363241
1,Denmark,Western Europe,2,7.5864,1.949406,1.547875,0.537302,0.734416,0.525221,0.208459,2.083766
2,Iceland,Western Europe,3,7.5296,1.925508,1.619666,0.559096,0.738164,0.187119,0.249635,2.250382
3,Israel,Middle East and Northern Africa,4,7.4729,1.833398,1.520674,0.576730,0.568518,0.158292,0.124048,2.691290
4,Netherlands,Western Europe,5,7.4030,1.942274,1.488228,0.545473,0.672327,0.394062,0.250547,2.110044
...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),Sub-Saharan Africa,133,3.2072,0.530779,0.783747,0.104758,0.375472,0.068287,0.182573,1.161580
133,Zimbabwe,Sub-Saharan Africa,134,3.2035,0.758279,0.880513,0.068653,0.362508,0.117115,0.111627,0.904856
134,Sierra Leone,Sub-Saharan Africa,135,3.1376,0.669699,0.540343,0.091811,0.370907,0.051077,0.192731,1.221006
135,Lebanon,Middle East and Northern Africa,136,2.3922,1.416999,0.475936,0.398308,0.122771,0.027208,0.060824,-0.109798
136,Afghanistan,Southern Asia,137,1.8590,0.644600,0.000000,0.086704,0.000000,0.058644,0.092965,0.976065

In [ ]:
df2015

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,Sub-Saharan Africa,155,3.340,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,Middle East and Northern Africa,156,3.006,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,Sub-Saharan Africa,157,2.905,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,Sub-Saharan Africa,158,2.839,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [ ]:
df2016

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,Southern Asia,154,3.360,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,Sub-Saharan Africa,155,3.303,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,Middle East and Northern Africa,156,3.069,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,Sub-Saharan Africa,157,2.905,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [ ]:
df2017

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Norway,Western Europe,1,7.537,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027
1,Denmark,Western Europe,2,7.522,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707
2,Iceland,Western Europe,3,7.504,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715
3,Switzerland,Western Europe,4,7.494,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716
4,Finland,Western Europe,5,7.469,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483,2.430182
...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,Sub-Saharan Africa,151,3.471,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756,0.540061
151,Syria,Middle East and Northern Africa,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1.061574
152,Tanzania,Sub-Saharan Africa,153,3.349,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256,0.621130
153,Burundi,Sub-Saharan Africa,154,2.905,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435,1.683024
154,Central African Republic,NaN,155,2.693,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005

In [ ]:
df2018

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Finland,Western Europe,1,7.6321,1.305095,1.592134,0.874454,0.680633,0.392961,0.191638,2.595186
1,Norway,Western Europe,2,7.5937,1.455627,1.582340,0.860763,0.686420,0.339687,0.285636,2.383242
2,Denmark,Western Europe,3,7.5553,1.351153,1.590453,0.867933,0.683251,0.407917,0.284392,2.370179
3,Iceland,Western Europe,4,7.4952,1.343301,1.644378,0.913802,0.676502,0.138019,0.353233,2.425990
4,Switzerland,Western Europe,5,7.4873,1.419727,1.548998,0.927076,0.659779,0.356677,0.255525,2.319529
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,Middle East and Northern Africa,152,3.3549,0.441527,1.072613,0.343216,0.243870,0.064146,0.083092,1.106474
152,Tanzania,Sub-Saharan Africa,153,3.3035,0.454864,0.991134,0.381297,0.480925,0.097195,0.270037,0.628085
153,South Sudan,Sub-Saharan Africa,154,3.2542,0.337370,0.607502,0.177460,0.111604,0.105675,0.223926,1.690625
154,Central African Republic,NaN,155,3.0830,0.023905,0.000000,0.010100,0.305280,0.038344,0.218356,2.487011
155,Burundi,Sub-Saharan Africa,156,2.9045,0.090806,0.626902,0.145325,0.064850,0.075953,0.148904,1.751794

In [ ]:
df2019

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Finland,Western Europe,1,7.7689,1.340243,1.587276,0.986145,0.595895,0.392913,0.152708,2.713678
1,Denmark,Western Europe,2,7.6001,1.383439,1.572595,0.996019,0.592356,0.410473,0.252320,2.392891
2,Norway,Western Europe,3,7.5539,1.487767,1.581548,1.028123,0.603500,0.340884,0.271304,2.240764
3,Iceland,Western Europe,4,7.4936,1.380163,1.623651,1.025653,0.590905,0.117980,0.354356,2.400876
4,Netherlands,Western Europe,5,7.4876,1.396020,1.521903,0.999314,0.557075,0.297978,0.322440,2.392895
...,...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,Sub-Saharan Africa,152,3.3338,0.359488,0.711048,0.613996,0.554570,0.410826,0.216655,0.467255
152,Tanzania,Sub-Saharan Africa,153,3.2307,0.475854,0.884855,0.498773,0.417151,0.147167,0.276294,0.530644
153,Afghanistan,Southern Asia,154,3.2033,0.349631,0.517003,0.360616,0.000000,0.024875,0.158151,1.793060
154,Central African Republic,NaN,155,3.0830,0.026408,0.000000,0.105346,0.225277,0.035268,0.235050,2.455649
155,South Sudan,Sub-Saharan Africa,156,2.8526,0.305843,0.574936,0.294648,0.010214,0.090529,0.202084,1.374341

In [ ]:
df2020

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia + residual
0,Finland,Western Europe,1,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,2,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,3,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,4,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,5,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,149,3.4759,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,Rwanda,Sub-Saharan Africa,150,3.3123,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,Zimbabwe,Sub-Saharan Africa,151,3.2992,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,South Sudan,Sub-Saharan Africa,152,2.8166,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,Afghanistan,South Asia,153,2.5669,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [ ]:
df2021

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia + residual
0,Finland,Western Europe,1,7.8421,1.446356,1.106192,0.740824,0.690577,0.124200,0.480524,3.253415
1,Denmark,Western Europe,2,7.6195,1.501548,1.108008,0.762862,0.686160,0.207615,0.484993,2.868296
2,Switzerland,Western Europe,3,7.5715,1.565899,1.079469,0.816415,0.653488,0.204040,0.413019,2.839148
3,Iceland,Western Europe,4,7.5539,1.482190,1.172279,0.772319,0.697701,0.292526,0.169940,2.966945
4,Netherlands,Western Europe,5,7.4640,1.501072,1.079151,0.753425,0.646585,0.302397,0.383531,2.797818
...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,145,3.5118,0.450848,0.730561,0.006992,0.405455,0.102819,0.015284,1.799821
145,Botswana,Sub-Saharan Africa,146,3.4665,1.099198,0.724478,0.339868,0.538626,0.027394,0.088468,0.648460
146,Rwanda,Sub-Saharan Africa,147,3.4147,0.363624,0.202183,0.406969,0.626681,0.227457,0.492669,1.095149
147,Zimbabwe,Sub-Saharan Africa,148,3.1448,0.456724,0.648552,0.243230,0.358907,0.157088,0.075471,1.204845
148,Afghanistan,South Asia,149,2.5229,0.370120,0.000000,0.126440,0.000000,0.121641,0.009569,1.895141

In [ ]:
df2022

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Finland,Western Europe,1,7.8210,1.891628,1.258108,0.775206,0.735590,0.533658,0.108733,2.518052
1,Denmark,Western Europe,2,7.6362,1.952595,1.242681,0.776644,0.718918,0.532079,0.187626,2.225632
2,Iceland,Western Europe,3,7.5575,1.935726,1.319914,0.802622,0.718194,0.191204,0.269616,2.320185
3,Switzerland,Western Europe,4,7.5116,2.025970,1.226074,0.822048,0.676947,0.461004,0.146822,2.152746
4,Netherlands,Western Europe,5,7.4149,1.944578,1.205848,0.786738,0.650682,0.419083,0.271076,2.136937
...,...,...,...,...,...,...,...,...,...,...,...
141,Botswana*,NaN,142,3.4711,1.502590,0.815473,0.279801,0.571353,0.101993,0.012459,0.187416
142,Rwanda*,NaN,143,3.2682,0.785252,0.132698,0.461527,0.621479,0.544236,0.186662,0.536299
143,Zimbabwe,Sub-Saharan Africa,144,2.9951,0.946604,0.690460,0.270086,0.329203,0.104943,0.106265,0.547529
144,Lebanon,Middle East and Northern Africa,145,2.9553,1.392068,0.497999,0.630964,0.102799,0.033761,0.082191,0.215537
145,Afghanistan,Southern Asia,146,2.4038,0.757994,0.000000,0.288626,0.000000,0.004882,0.088873,1.263403

In [ ]:
df2023

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Finland,Western Europe,1,7.8042,1.888380,1.584900,0.534574,0.771510,0.535299,0.126331,2.363241
1,Denmark,Western Europe,2,7.5864,1.949406,1.547875,0.537302,0.734416,0.525221,0.208459,2.083766
2,Iceland,Western Europe,3,7.5296,1.925508,1.619666,0.559096,0.738164,0.187119,0.249635,2.250382
3,Israel,Middle East and Northern Africa,4,7.4729,1.833398,1.520674,0.576730,0.568518,0.158292,0.124048,2.691290
4,Netherlands,Western Europe,5,7.4030,1.942274,1.488228,0.545473,0.672327,0.394062,0.250547,2.110044
...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),Sub-Saharan Africa,133,3.2072,0.530779,0.783747,0.104758,0.375472,0.068287,0.182573,1.161580
133,Zimbabwe,Sub-Saharan Africa,134,3.2035,0.758279,0.880513,0.068653,0.362508,0.117115,0.111627,0.904856
134,Sierra Leone,Sub-Saharan Africa,135,3.1376,0.669699,0.540343,0.091811,0.370907,0.051077,0.192731,1.221006
135,Lebanon,Middle East and Northern Africa,136,2.3922,1.416999,0.475936,0.398308,0.122771,0.027208,0.060824,-0.109798
136,Afghanistan,Southern Asia,137,1.8590,0.644600,0.000000,0.086704,0.000000,0.058644,0.092965,0.976065

In [ ]:
df2023[df2023.isna().any(axis=1)]

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
17,Czechia,NaN,18,6.8452,1.823469,1.543999,0.477349,0.693139,0.050239,0.157766,2.099239
26,Taiwan Province of China,NaN,27,6.5354,1.890335,1.371842,0.492341,0.561938,0.177711,0.067239,1.974016
81,Hong Kong S.A.R. of China,NaN,82,5.3085,1.950940,1.201336,0.701590,0.406797,0.389993,0.122539,0.535256
86,North Macedonia,NaN,87,5.2536,1.497871,1.170578,0.407886,0.515419,0.019607,0.206848,1.435431
96,Mozambique,NaN,97,4.9540,0.570097,0.885309,0.000000,0.625214,0.192410,0.161483,2.519486
98,State of Palestine,NaN,99,4.9078,1.143960,1.308868,NaN,0.416328,0.066824,0.065409,NaN
105,Turkiye,NaN,106,4.6135,1.714366,1.147928,0.466803,0.124665,0.096117,0.095108,0.968547
118,Gambia,NaN,119,4.2794,0.760724,0.613659,0.173556,0.285875,0.033252,0.331844,2.080531

In [ ]:
df2022[df2022.isna().any(axis=1)]

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
5,Luxembourg*,NaN,6,7.4040,2.209395,1.154525,0.790365,0.699728,0.388120,0.120203,2.041680
17,Czechia,NaN,18,6.9198,1.815016,1.260081,0.715006,0.660386,0.048207,0.158460,2.262640
25,Taiwan Province of China,NaN,26,6.5125,1.896887,1.095204,0.732674,0.542251,0.168240,0.075033,2.002191
38,Guatemala*,NaN,39,6.2622,1.273642,0.831088,0.522102,0.662154,0.114789,0.112233,2.746166
49,Kuwait*,NaN,50,6.1061,1.903865,0.983288,0.747096,0.617335,0.146642,0.086954,1.620939
64,Belarus*,NaN,65,5.8215,1.561945,1.156542,0.628830,0.341836,0.282011,0.039550,1.810738
77,Turkmenistan*,NaN,78,5.4743,1.484313,1.318955,0.516333,0.648984,0.031605,0.314299,1.159811
78,North Cyprus*,NaN,79,5.4666,1.815065,0.888054,0.819165,0.522693,0.213033,0.130266,1.078338
80,Hong Kong S.A.R. of China,NaN,81,5.4248,1.957330,0.954267,0.941829,0.400340,0.382751,0.146722,0.641555
85,Libya*,NaN,86,5.3302,1.475776,0.942594,0.605754,0.476543,0.179434,0.105959,1.544163
88,North Macedonia,NaN,89,5.1990,1.504625,0.862629,0.637380,0.487500,0.031002,0.215123,1.460712
91,Azerbaijan*,NaN,92,5.1734,1.457979,1.093035,0.559601,0.600895,0.340661,0.023429,1.097789
92,Gambia*,NaN,93,5.1636,0.784830,0.620554,0.369221,0.367387,0.102532,0.388032,2.531070
96,Liberia*,NaN,97,5.1215,0.635615,0.670007,0.308646,0.405378,0.079559,0.177869,2.844388
98,Congo,NaN,99,5.0752,0.950383,0.405160,0.355222,0.430860,0.145644,0.130043,2.657927
100,Mozambique,NaN,101,5.0483,0.578288,0.659684,0.191080,0.592992,0.199687,0.185126,2.641415
103,Niger*,NaN,104,5.0035,0.569873,0.560071,0.325953,0.571325,0.144813,0.164628,2.666880
115,Comoros*,NaN,116,4.6086,0.899388,0.476141,0.424028,0.185309,0.125326,0.194503,2.303922
121,Palestinian Territories*,NaN,122,4.4825,1.147926,0.957225,0.520660,0.336379,0.079447,0.073156,1.367745
124,"Eswatini, Kingdom of*",NaN,125,4.3961,1.273627,0.786265,0.196882,0.259250,0.154094,0.037638,1.688359
127,Madagascar*,NaN,128,4.3391,0.670333,0.644561,0.377875,0.202051,0.153518,0.142967,2.147783
129,Chad*,NaN,130,4.2508,0.661558,0.506288,0.224994,0.180287,0.076946,0.181592,2.419135
131,Yemen*,NaN,132,4.1969,0.691439,1.042592,0.383644,0.329589,0.097885,0.090387,1.561377
132,Mauritania*,NaN,133,4.1526,1.100187,0.864883,0.449989,0.303937,0.138468,0.088364,1.206791
140,Lesotho*,NaN,141,3.5118,0.838667,0.847958,0.000000,0.418751,0.018400,0.076067,1.311937
141,Botswana*,NaN,142,3.4711,1.502590,0.815473,0.279801,0.571353,0.101993,0.012459,0.187416
142,Rwanda*,NaN,143,3.2682,0.785252,0.132698,0.461527,0.621479,0.544236,0.186662,0.536299

In [ ]:
df2022.shape
df2022.to_csv('2022.csv', index=False )

In [ ]:
df2022['Region'].unique()

array(['Western Europe', nan, 'Middle East and Northern Africa',
       'Australia and New Zealand', 'North America',
       'Central and Eastern Europe', 'Latin America and Caribbean',
       'Southeastern Asia', 'Sub-Saharan Africa', 'Eastern Asia',
       'Southern Asia'], dtype=object)

In [ ]:
df2022 = pd.read_csv('2022_cleaned.csv')
df2022

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Finland,Western Europe,1,7.8210,1.891628,1.258108,0.775206,0.735590,0.533658,0.108733,2.518052
1,Denmark,Western Europe,2,7.6362,1.952595,1.242681,0.776644,0.718918,0.532079,0.187626,2.225632
2,Iceland,Western Europe,3,7.5575,1.935726,1.319914,0.802622,0.718194,0.191204,0.269616,2.320185
3,Switzerland,Western Europe,4,7.5116,2.025970,1.226074,0.822048,0.676947,0.461004,0.146822,2.152746
4,Netherlands,Western Europe,5,7.4149,1.944578,1.205848,0.786738,0.650682,0.419083,0.271076,2.136937
...,...,...,...,...,...,...,...,...,...,...,...
141,Botswana*,Sub-Saharan Africa,142,3.4711,1.502590,0.815473,0.279801,0.571353,0.101993,0.012459,0.187416
142,Rwanda*,Sub-Saharan Africa,143,3.2682,0.785252,0.132698,0.461527,0.621479,0.544236,0.186662,0.536299
143,Zimbabwe,Sub-Saharan Africa,144,2.9951,0.946604,0.690460,0.270086,0.329203,0.104943,0.106265,0.547529
144,Lebanon,Middle East and Northern Africa,145,2.9553,1.392068,0.497999,0.630964,0.102799,0.033761,0.082191,0.215537
145,Afghanistan,Southern Asia,146,2.4038,0.757994,0.000000,0.288626,0.000000,0.004882,0.088873,1.263403

In [ ]:
# Perform the merge, specifying 'suffixes' to avoid duplicate columns
df2023 = pd.merge(df2023, df2022[['Country', 'Region']], on='Country', how='left', suffixes=('_df2023', '_df2022'))

# Fill missing values in the 'Region_df2023' column with values from 'Region_df2022'
df2023['Region_df2023'] = df2023['Region_df2023'].fillna(df2023['Region_df2022'])

# Drop the additional 'Region_df2022' column if needed
df2023.drop(columns=['Region_df2022'], inplace=True)

# Rename the remaining 'Region_df2023' column to 'Region'
df2023.rename(columns={'Region_df2023': 'Region'}, inplace=True)

In [ ]:
df2023[df2023.isna().any(axis=1)]

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
98,State of Palestine,NaN,99,4.9078,1.143960,1.308868,NaN,0.416328,0.066824,0.065409,NaN
105,Turkiye,NaN,106,4.6135,1.714366,1.147928,0.466803,0.124665,0.096117,0.095108,0.968547
118,Gambia,NaN,119,4.2794,0.760724,0.613659,0.173556,0.285875,0.033252,0.331844,2.080531

In [ ]:
# Dictionary mapping countries to regions based on available data
region_mapping = {
    'State of Palestine': 'Middle East and Northern Africa',
    'Turkiye': 'Middle East and Northern Africa',
    'Gambia': 'Sub-Saharan Africa',
    # Add more countries and their corresponding regions as needed
}

# Fill missing 'Region' values based on the dictionary mapping
df2023['Region'] = df2023['Region'].fillna(df2023['Country'].map(region_mapping))

In [ ]:
df2023[df2023.isna().any(axis=1)]

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
98,State of Palestine,Middle East and Northern Africa,99,4.9078,1.14396,1.308868,NaN,0.416328,0.066824,0.065409,NaN

In [ ]:
df2023.dropna(inplace=True)

In [ ]:
df2023[df2023.isna().any(axis=1)]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, Economy (GDP per Capita), Family, Health (Life Expectancy), Freedom, Trust (Government Corruption), Generosity, Dystopia Residual]
Index: []

In [ ]:
df2023.to_csv('2023_cleaned.csv', index=False)

In [ ]:
df2021[df2021.isna().any(axis=1)]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, Economy (GDP per Capita), Family, Health (Life Expectancy), Freedom, Generosity, Trust (Government Corruption), Dystopia + residual]
Index: []

In [ ]:
df2021.to_csv('2021_cleaned.csv', index=False)

In [ ]:
df2020[df2020.isna().any(axis=1)]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, Economy (GDP per Capita), Family, Health (Life Expectancy), Freedom, Generosity, Trust (Government Corruption), Dystopia + residual]
Index: []

In [ ]:
df2020.to_csv('2020_cleaned.csv', index=False)

In [ ]:
df2019[df2019.isna().any(axis=1)]

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
24,Taiwan Province of China,NaN,25,6.4462,1.368087,1.430416,0.913703,0.350553,0.096796,0.241697,2.044986
75,Hong Kong S.A.R. of China,NaN,76,5.4304,1.437999,1.276593,1.122140,0.439628,0.287330,0.257671,0.609069
119,Gambia,NaN,120,4.5163,0.307813,0.939059,0.427996,0.382251,0.167130,0.268641,2.023422
122,Mozambique,NaN,123,4.4662,0.203645,0.985662,0.390127,0.493750,0.137762,0.197349,2.057935
134,Swaziland,NaN,135,4.2116,0.810798,1.149239,0.000000,0.313344,0.134683,0.073977,1.729524
143,Lesotho,NaN,144,3.8019,0.488944,1.169010,0.167731,0.358645,0.093269,0.107374,1.416887
154,Central African Republic,NaN,155,3.0830,0.026408,0.000000,0.105346,0.225277,0.035268,0.235050,2.455649

In [ ]:
# Perform the merge, specifying 'suffixes' to avoid duplicate columns
df2019 = pd.merge(df2019, df2022[['Country', 'Region']], on='Country', how='left', suffixes=('_df2023', '_df2022'))

# Fill missing values in the 'Region_df2023' column with values from 'Region_df2022'
df2019['Region_df2023'] = df2019['Region_df2023'].fillna(df2019['Region_df2022'])

# Drop the additional 'Region_df2022' column if needed
df2019.drop(columns=['Region_df2022'], inplace=True)

# Rename the remaining 'Region_df2023' column to 'Region'
df2019.rename(columns={'Region_df2023': 'Region'}, inplace=True)
df2019

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Finland,Western Europe,1,7.7689,1.340243,1.587276,0.986145,0.595895,0.392913,0.152708,2.713678
1,Denmark,Western Europe,2,7.6001,1.383439,1.572595,0.996019,0.592356,0.410473,0.252320,2.392891
2,Norway,Western Europe,3,7.5539,1.487767,1.581548,1.028123,0.603500,0.340884,0.271304,2.240764
3,Iceland,Western Europe,4,7.4936,1.380163,1.623651,1.025653,0.590905,0.117980,0.354356,2.400876
4,Netherlands,Western Europe,5,7.4876,1.396020,1.521903,0.999314,0.557075,0.297978,0.322440,2.392895
...,...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,Sub-Saharan Africa,152,3.3338,0.359488,0.711048,0.613996,0.554570,0.410826,0.216655,0.467255
152,Tanzania,Sub-Saharan Africa,153,3.2307,0.475854,0.884855,0.498773,0.417151,0.147167,0.276294,0.530644
153,Afghanistan,Southern Asia,154,3.2033,0.349631,0.517003,0.360616,0.000000,0.024875,0.158151,1.793060
154,Central African Republic,NaN,155,3.0830,0.026408,0.000000,0.105346,0.225277,0.035268,0.235050,2.455649
155,South Sudan,Sub-Saharan Africa,156,2.8526,0.305843,0.574936,0.294648,0.010214,0.090529,0.202084,1.374341

In [ ]:
# Dictionary mapping countries to regions based on available data
region_mapping = {
    'State of Palestine': 'Middle East and Northern Africa',
    'Turkiye': 'Middle East and Northern Africa',
    'Gambia': 'Sub-Saharan Africa',
    'Swaziland': 'Sub-Saharan Africa',
    'Lesotho': 'Sub-Saharan Africa',
    'Central African Republic': 'Sub-Saharan Africa'
    # Add more countries and their corresponding regions as needed
}

# Fill missing 'Region' values based on the dictionary mapping
df2019['Region'] = df2019['Region'].fillna(df2019['Country'].map(region_mapping))
df2019[df2019.isna().any(axis=1)]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, Economy (GDP per Capita), Family, Health (Life Expectancy), Freedom, Trust (Government Corruption), Generosity, Dystopia Residual]
Index: []

In [ ]:
df2019.to_csv('2019_cleaned.csv', index=False)

In [ ]:
df2018[df2018.isna().any(axis=1)]

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
25,Taiwan Province of China,NaN,26,6.4406,1.365053,1.435968,0.857375,0.417559,0.077859,0.150619,2.136127
37,Trinidad & Tobago,NaN,38,6.1919,1.222706,1.492152,0.563752,0.575081,0.018647,0.171070,2.148453
57,Northern Cyprus,NaN,58,5.8348,1.228816,1.211011,0.909132,0.494897,0.153539,0.178681,1.658751
75,"Hong Kong SAR, China",NaN,76,5.4304,1.405062,1.289982,1.029650,0.524217,0.291431,0.246465,0.643622
122,Mozambique,NaN,123,4.4166,0.198004,0.901897,0.172653,0.530866,0.158241,0.205628,2.249320
140,Lesotho,NaN,141,3.8082,0.472480,1.214946,0.078981,0.422942,0.111505,0.115610,1.391742
154,Central African Republic,NaN,155,3.0830,0.023905,0.000000,0.010100,0.305280,0.038344,0.218356,2.487011

In [ ]:
# Perform the merge, specifying 'suffixes' to avoid duplicate columns
df2018 = pd.merge(df2018, df2019[['Country', 'Region']], on='Country', how='left', suffixes=('_df2023', '_df2022'))

# Fill missing values in the 'Region_df2023' column with values from 'Region_df2022'
df2018['Region_df2023'] = df2018['Region_df2023'].fillna(df2018['Region_df2022'])

# Drop the additional 'Region_df2022' column if needed
df2018.drop(columns=['Region_df2022'], inplace=True)

# Rename the remaining 'Region_df2023' column to 'Region'
df2018.rename(columns={'Region_df2023': 'Region'}, inplace=True)

df2018[df2018.isna().any(axis=1)]

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
37,Trinidad & Tobago,NaN,38,6.1919,1.222706,1.492152,0.563752,0.575081,0.018647,0.171070,2.148453
57,Northern Cyprus,NaN,58,5.8348,1.228816,1.211011,0.909132,0.494897,0.153539,0.178681,1.658751
75,"Hong Kong SAR, China",NaN,76,5.4304,1.405062,1.289982,1.029650,0.524217,0.291431,0.246465,0.643622

In [ ]:
# Add missing countries and their corresponding regions to the dictionary
region_mapping.update({
    'Trinidad & Tobago': 'Latin America and Caribbean',
    'Northern Cyprus': 'Middle East and Northern Africa',
    'Hong Kong SAR, China': 'Eastern Asia'
})

# Fill missing 'Region' values based on the updated dictionary mapping
df2018['Region'] = df2018['Region'].fillna(df2018['Country'].map(region_mapping))

In [ ]:
df2018.to_csv('2018_cleaned.csv', index=False)

In [ ]:
df2017[df2017.isna().any(axis=1)]

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
32,Taiwan Province of China,NaN,33,6.422,1.433627,1.384565,0.793984,0.361467,0.063829,0.258360,2.126607
70,"Hong Kong S.A.R., China",NaN,71,5.472,1.551675,1.262791,0.943062,0.490969,0.293934,0.374466,0.554633
112,Mozambique,NaN,113,4.550,0.234306,0.870701,0.106654,0.480791,0.179436,0.322228,2.355651
138,Lesotho,NaN,139,3.808,0.521021,1.190095,0.000000,0.390661,0.119095,0.157497,1.429835
154,Central African Republic,NaN,155,2.693,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005

In [ ]:
# Perform the merge, specifying 'suffixes' to avoid duplicate columns
df2017 = pd.merge(df2017, df2018[['Country', 'Region']], on='Country', how='left', suffixes=('_df2023', '_df2022'))

# Fill missing values in the 'Region_df2023' column with values from 'Region_df2022'
df2017['Region_df2023'] = df2017['Region_df2023'].fillna(df2017['Region_df2022'])

# Drop the additional 'Region_df2022' column if needed
df2017.drop(columns=['Region_df2022'], inplace=True)

# Rename the remaining 'Region_df2023' column to 'Region'
df2017.rename(columns={'Region_df2023': 'Region'}, inplace=True)

df2017[df2017.isna().any(axis=1)]

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
70,"Hong Kong S.A.R., China",NaN,71,5.472,1.551675,1.262791,0.943062,0.490969,0.293934,0.374466,0.554633

In [ ]:
region_mapping.update({
    'Hong Kong S.A.R., China': 'Eastern Asia'
})

# Fill missing 'Region' values based on the updated dictionary mapping
df2017['Region'] = df2017['Region'].fillna(df2017['Country'].map(region_mapping))

In [ ]:

df2017[df2017.isna().any(axis=1)]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, Economy (GDP per Capita), Family, Health (Life Expectancy), Freedom, Trust (Government Corruption), Generosity, Dystopia Residual]
Index: []

In [ ]:
df2017.to_csv('df2017_cleaned.csv', index='False')

In [ ]:
df2016[df2016.isna().any(axis=1)]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, Economy (GDP per Capita), Family, Health (Life Expectancy), Freedom, Trust (Government Corruption), Generosity, Dystopia Residual]
Index: []

In [ ]:
df2016.to_csv('2016_cleaned.csv', index=False)

In [ ]:
df2015[df2015.isna().any(axis=1)]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, Economy (GDP per Capita), Family, Health (Life Expectancy), Freedom, Trust (Government Corruption), Generosity, Dystopia Residual]
Index: []

In [ ]:
df2015.to_csv('2015_cleaned.csv', index=False)

In [ ]:
import plotly.express as px

In [ ]:
# start on visualisations

def create_choropleth(dataset):
    fig = px.choropleth(dataset, 
                    locations="Country", 
                    locationmode='country names',
                    color="Happiness Score",  # Color represents Happiness Score
                    hover_name="Country", 
                    # animation_frame="Year",  # Year is the column representing the years in your dataset
                    color_continuous_scale=px.colors.sequential.Plasma,  # Choose the color scale
                    projection="natural earth")  # Choose the map projection style

    # Set the layout title and show the figure
    fig.update_layout(title_text='World Happiness Index (2015-2023)',
                    geo=dict(showcoastlines=True, coastlinecolor="Black", showland=True, landcolor="white",
                            showframe=False, projection_type="mercator"))

    # Show the animation
    fig.show()

In [ ]:
create_choropleth(df2015)

In [ ]:
%pip install --upgrade plotly

Requirement already satisfied: plotly in /Users/sean/opt/anaconda3/lib/python3.8/site-packages (5.17.0)
Collecting plotly
  Downloading plotly-5.18.0-py3-none-any.whl (15.6 MB)
     |████████████████████████████████| 15.6 MB 2.3 MB/s eta 0:00:01
Requirement already satisfied: packaging in /Users/sean/opt/anaconda3/lib/python3.8/site-packages (from plotly) (20.9)
Requirement already satisfied: tenacity>=6.2.0 in /Users/sean/opt/anaconda3/lib/python3.8/site-packages (from plotly) (8.2.3)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/sean/opt/anaconda3/lib/python3.8/site-packages (from packaging->plotly) (2.4.7)
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.17.0
    Uninstalling plotly-5.17.0:
      Successfully uninstalled plotly-5.17.0
Successfully installed plotly-5.18.0
Note: you may need to restart the kernel to use updated packages.